"""Add financial label

Revision ID: d58648ac72d5
Revises: 42c194104c03
Create Date: 2019-06-17 14:14:51.106431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58648ac72d5'
down_revision = '42c194104c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('years', sa.Column('financial_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('years', 'financial_label')
    # ### end Alembic commands ###
