"""Keep track off processed

Revision ID: 3590c8893523
Revises: d58648ac72d5
Create Date: 2019-06-18 14:52:04.644708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3590c8893523'
down_revision = 'd58648ac72d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_processed')
    # ### end Alembic commands ###
